title: "7-Lens Innovation Blog"
author: "Chotchuang"
description: "Exploring the 7-Lens Innovation Cycle"
baseurl: ""
url: "https://bluexprice.github.io/7len"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
permalink: /:title/
